
### data assimilation settings ###
n_en: 20 # number of ensembles for data assimilation

start: '2014-06-01'
stop: '2015-01-01'
forecast_horizon: 10 # days to forecast

# metadata settings
# change this to reflect the actual forecast issue time
# forecast_issue_time: '2020-03-10'
# ID that applies to set of forecasts
forecast_project_id: 'DRB_DA_SNTemp_20201023'
# ForecastProject_id represents the launch of an automated, iterative forecast.  It is created
# each time a human modifies the forecast code.  It can be a DOI because this is the level that
# we envision citations occuring.
#
# Forecast_id represents each forecast cycle within a ForecastProject_id
#
# For example, if you have a forecast code base on GitHub and launch a forecast from that code that
# runs daily for 365 days, then there will be one ForecastProject_id and 365 Forecast_ids. A paper
# analyzing the forecasts would cite the ForecastProject_id.
# see: https://github.com/eco4cast/EFIstandards/blob/e203992e6655723a10fc5cba5a64fd733bd903d0/vignettes/flare-metadata-example.Rmd#L23-L33

#ID that applies to the specific forecast. Make new ID for every new forecast - will need to update based on
# forecast_id: 'fodsiajafa2424oji'

params_to_update: [] # parameters we want to calibrate

param_groups:
  param:
  - ss_tau
  - gw_tau
  - albedo
  - melt_temp
  min:
  - 1.0
  - 10.0
  - 0.0
  - 0.0
  max:
  - 50.0
  - 150.0
  - 1.0
  - 10.0
  sd:
  - 2.0
  - 6.0
  - .05
  - 1.0
  units:
  - days
  - days
  - decimal fraction
  - degrees C
  longname:
  - Average residence time of subsurface interflow
  - Average residence time in groundwater flow
  - Short-wave solar radiation reflected by streams
  - Temperature at which snowmelt enters a stream
  prec:
  - integer
  - integer
  - float
  - float


states_to_update: ['seg_tave_water', 'gw_sum', 'ss_sum']
states:
  state:
  - seg_tave_water
  - gw_sum
  - ss_sum
  units:
  - degrees C
  - degrees C
  - degrees C
  longname:
  - daily mean stream segment water temperature
  - groundwater temperature moving average
  - shallow subsurface temperature moving average
  prec:
  - float
  - float
  - float

# forecasted drivers from NOAA GEFS
drivers:
  driver:
  - prcp
  - tmax
  - tmin
  units:
  - inches
  - degrees F
  - degrees F
  longname:
  - daily accumulated precipitation
  - maximum daily temperature
  - minimum daily temperature
  prec:
  - float
  - float
  - float

sntemp_output: ['seg_tave_air', 'seg_rain', 'seg_tave_water', 'seg_outflow', 'seg_tave_gw', 'seg_tave_sroff', 'seg_tave_ss',
'seg_tave_upstream', 'seg_upstream_inflow', 'seginc_gwflow', 'seginc_potet', 'seginc_sroff', 'seginc_ssflow',
'seginc_swrad', 'seg_humid', 'seg_shade', 'seg_ccov', 'seg_width']


